### ISSUE TITLE
Bokstavsrad skrollar inte till bokstavsgrupp

### ISSUE THREAD

**Issue by dnjstrom** [LabVastmanland/methodlist#16]
Det finns implementerat så man kan klicka på en bokstav och webläsaren hoppar ner, men för att det ska funka måste man använda html5mode vilket i sin tur kräver en custom domän.

Antingen:
1. Införskaffas en domän som vi kan använda för siten
2. struntar vi i att man inte kan länka direkt till en bokstavsgrupp och skrollar ner med javascript

.. min röst faller på alternativ nummer 2. 👍

**Comment by gustavsobel** [comment]
oavsett så ska vi väl ha en custom domän, men sen kanske 2:an är enklast ändå?

**Comment by gustavsobel** [comment]
Sen skulle vi kanske behöva en "till toppen"-grej
