### ISSUE TITLE
Icke-stämmande analyser

### ISSUE THREAD

**Issue by gustavsobel** [LabVastmanland/methodlist#22]
På dessa analyser verkar texten ha "hoppat" en rubrik uppåt:
Under A:
ACTH, ADA (båda), ALA, Aldosteron (P-), Allergener specifika, Aluminium, Alzheimermarkörer, Amatoxin, Amikacin, Amylas (U-), Amyloid beta, Anti-intercellulärsubstans, Antitrypsin, Apoliprotein A1, APS1-diagnostik, Array-CGH, ASCA

**Comment by gustavsobel** [comment]
Under B:
Basalmembran-antikroppar, Beta-2-Glykoprotein-1-antikroppar, Binjurebark (anti-), Bly (båda),

**Comment by gustavsobel** [comment]
Under C:
C1-inhibitor, CA 15-3, CA 19-9, CA 72-4, Calciumjon-aktivitet, CALR mutationsanalys, CD-sens, Ceruloplasmin, Chititriosidas, Chromogranin, C-peptid (beställningsbar i Cosmic S-), CrossLaps beta,

**Comment by gustavsobel** [comment]
Oftast verkar det vara på något sätt att den slänger in rubriken "Anges på remiss" även fast den ska vara tom, och således flyttar upp alla texter efter det

**Comment by gustavsobel** [comment]
Under #:
21-Hydroxylas-antikroppar

**Comment by gustavsobel** [comment]
Under D:
DHEA, Diaminoxias, D-Laktat (U-),

**Comment by gustavsobel** [comment]
Under E:
Erytropoetin

**Comment by gustavsobel** [comment]
Under F:
Faktor VIII (aktivitet), Familjär Amyloid Polyneuropati, FGF-23, Fria fettsyror, Fria lätta Ig-kedjor

**Comment by gustavsobel** [comment]
Under G:
G-6-PD, GAD-antikroppar, Gastrin, Glia-fibrillärt surt protein, Globotriaosylceramid (båda), Glykoproteinhormon, Guld

**Comment by gustavsobel** [comment]
Under H:
Heparin-antikroppar, HLA-antikroppar, Homocystein och Metionin, HR-urticaria test, Hydroxiprogesteron

**Comment by gustavsobel** [comment]
Under I:
IA2-antikroppar, IgA-Fibronektin komplex, IGF-1, IGFBP-3 (till Tillväxtlab, Sahlgrenska), IgG subklasser, IgVH mutationsstatus, Immunfenotypning (B-/Benm-/Csv-), Insulin, Interleukin-5, Intrinsic faktor-AK, Isoagglutininer, Isocyanat-ak, Isopropanol

**Comment by gustavsobel** [comment]
Under K:
Kalcitonin, Kardiolipin-antikroppar, Koagulationsfaktor VIII (genetisk utredning), Kobolt, Komplementscreen, Koppar (S-), Kortisol (Saliv-), Krom, Kvicksilver

**Comment by gustavsobel** [comment]
Under L:
LD-isoenzym, Levonorgestrel, Lipoprotein (a), Lupusantikoagulans, Lysozym (U-)

**Comment by dnjstrom** [comment]
Vi byter parsing-metod från .htm till .csv (UTF-8) så slipper vi nog mycket av det här :)

**Comment by dnjstrom** [comment]
Har bytt till UTF-8 csv listan nu, men den du skickade hade fel encoding iaf.. Får labba lite till med dataformatet för exporten. Tänk också på att den försöker exportera överflödiga kolumner, så om du gör statistik - lägg in den på ett separat blad istället för att ha den på samma sidan som "datan".
