### ISSUE TITLE
Använda sig av radbrytning

### ISSUE THREAD

**Issue by gustavsobel** [LabVastmanland/methodlist#25]
Går det att använda sig av radbrytning/styckesindelning i texterna. Just nu hamnar ju allt i en lång flytande text.

**Comment by dnjstrom** [comment]
Det verkar som att CSV-parsningen tar bort nyrader. På dokumentationen ser det dock ut som att det inte borde vara ett problem.. men kan vara jag som tolkar det fel. Känns bökigt att ändra i eftersom alternativet antagligen är att implementera csv-parsning själva.. Något vi kan göra men som är ganska mekkigt. 😕

**Comment by gustavsobel** [comment]
Just nu tolkar den radbrytningar som ingenting. Dvs det saknas ett mellanslag mellan meningar där radbrytningar förekommer. 
"[...] rör (lila propp).Det är viktigt att [...]"

**Comment by gustavsobel** [comment]
dock verkar det som attt när man copy-paste:ar det så finns där ett mellanslag...

**Comment by dnjstrom** [comment]
Urk. Det betyder att det är ännu ett encoding problem :/
