### ISSUE TITLE
Text för footern

### ISSUE THREAD

**Issue by gustavsobel** [LabVastmanland/methodlist#26]
Jag tänker mig att det kan stå något i stil med

Klinisk kemi | Västmanlands sjukhus Västerås, Ingång 1, plan 2 | 021-17 35 50 | Ansvarig utgivare: Namn Namnesson

(allt på samma rad)

**Comment by gustavsobel** [comment]
Vore ju najs att få in våra namn också...några förslag?
Typ 
© Gustav Sobel och Daniel Ström 2016
(Får man copywrite:a utan att ha gjort det officiellt?)

**Comment by gustavsobel** [comment]
Ansvarig utgivare Per Bjellerup

**Comment by dnjstrom** [comment]
Googlade det och copyright är bara det engelska ordet för upphovsrätt - alla verk är upphovsrättsskyddade by default: http://www.javascript.nu/copy.shtml
