### ISSUE TITLE
Konstig bar som dyker upp

### ISSUE THREAD

**Issue by gustavsobel** [LabVastmanland/methodlist#30]
se bild
![screen shot 2016-08-02 at 18 44 37](https://cloud.githubusercontent.com/assets/20255952/17337032/3684edc6-58e1-11e6-852c-1777ac5cf0f9.png)

**Comment by gustavsobel** [comment]
både i chrome och firefox

**Comment by dnjstrom** [comment]
Testa att ladda om sidan ett par gånger (eller shift-R). Jag tror det kan vara artefakter för att sidan inte laddat om ordentligt.. (Vanligtvis laddas inte allt om utan bara det som läsaren tror är nytt). Du kan också testa att öppna sidan i inkognito-mode. Funkar det då?

**Comment by dnjstrom** [comment]
Det ser alltså inte ut så för mig i chrome

**Comment by gustavsobel** [comment]
undrar om det är nån plugin eller nåt hos mig som stökar då, för både chrome, safari och firefox har artefakterna, oavsett omladdningar

**Comment by gustavsobel** [comment]
Kollade på brorsans dator igår, och den ser lika dan ut där

**Comment by dnjstrom** [comment]
Weird.. Vad skiljer våra system åt då? Operativsystem? När vi träffas på
torsdag, kan du ta med en dator som det ser konstigt ut på, så jag kan
kolla vad som ger artefakterna?

**Comment by dnjstrom** [comment]
Kan vara en scroll-bar... Kolla igen! :)
