### ISSUE TITLE
Analyser öppnas längst ner på sidan

### ISSUE THREAD

**Issue by gustavsobel** [LabVastmanland/methodlist#32]
I alla fall på mobilen, när man öppnar en analys så hamnar man längst ner på sidan, vid "uppdaterat"-rubriken, och måste således scrolla sig upp varje gång.
Detta gäller inte när man söker eller när man valt en analys från toppen i listan - det verkar som om telefonen "sparar" ner-scrollningen från förra sidan?

**Comment by dnjstrom** [comment]
Ah, det problemet tror jag att jag stött på tidigare. Det borde inte vara
något problem att fixa.
