### ISSUE TITLE
När den pekats - Logga till "appen"

### ISSUE THREAD

**Issue by gustavsobel** [LabVastmanland/methodlist#33]
Om man nu vill ha en skrivbordslänk, eller "laddar ner" sidan som en app i telefonen, finns det nåt sätt för oss att bestämma hur den kommer se ut? Att den automatiskt blir typ den där blodsdroppen och "armarna"?

**Comment by dnjstrom** [comment]
Mmmm, det finns något som heter "favicon" som även är den ikonen man ser i
tabben när man har sidan öppen. Om du fixar en ikon i lämplig storlek -
minst 260x260 - så kan jag lägga in den.

**Comment by gustavsobel** [comment]
[
![klinkemsmall](https://cloud.githubusercontent.com/assets/20255952/17493562/34eab55c-5db1-11e6-8f78-f69405bd934b.jpg)
](url)

**Comment by gustavsobel** [comment]
kan ju testa

**Comment by gustavsobel** [comment]
Jag minns inte, är bilden en png utan bakgrund? Det märkliga är nämligen att på telefonen blir bakgrunden inte vit utan svart. Det samma gäller för iPaden. 
På skrivbordet på datorn blir den jättesnygg dock!
