### ISSUE TITLE
Skapa en dynamisk prislista

### ISSUE THREAD

**Issue by gustavsobel** [LabVastmanland/methodlist#37]
Exempelvis såhär:
I den nya listan kommer det troligtvis finnas en rubrik som heter "Pris". Just nu ligger dokumentet "Prislista" som ett eget dokument, som måste uppdateras på eget håll. Skulle det vara möjligt att ha en länk, precis som nu, men som genererar en ny lista med de proverna som har ett pris. Alltså så att man bara behöver uppdatera pris på ett enda ställe - i masterlistan (som den nu heter).
Jag inser att det här är en rätt galen idé som säkert är mycket mer jobb än det är värt, men skulle det ens gå?

**Comment by gustavsobel** [comment]
vi struntar i detta, skulle vara för krångligt

**Comment by dnjstrom** [comment]
Hmmm, det skulle absolut gå, även om det inte skulle vara världens
snyggaste lista. Jag har genererat Excel-filer förut så om det är något vi
vill ha så visst. :)
