### ISSUE TITLE
Även inaktiva länkar "lyser upp" when hoovered

### ISSUE THREAD

**Issue by gustavsobel** [LabVastmanland/methodlist#40]
När man för muspekaren över inaktiva bokstavslänkar (ex X och Y) så blir de också mörklila, precis som alla andra länkar. Dock är ju fortfarande muspekaren en pil och inte en hand, så det är rätt lugnt

**Comment by dnjstrom** [comment]
Hmmm, det här ser inte jag i chrome :P
