### ISSUE TITLE
Listan ej i bokstavsordning

### ISSUE THREAD

**Issue by gustavsobel** [LabVastmanland/methodlist#41]
´Just nu är det så att listan på förstasidan ligger i ordningen som analyserna ligger i excel-dokumentet - dvs är inte excel-dokumentet i bokstavsordning, är inte listan det heller. Går det enkelt att fixa, eller får man helt enkelt se till att listan är sorterad på boksstavsordning när man exporterar den?

**Comment by dnjstrom** [comment]
Jag kan justera sorteringen på min sida. 👍
