### ISSUE TITLE
Skulle en "överblicks-banner" vara möjlig att skapa?

### ISSUE THREAD

**Issue by gustavsobel** [LabVastmanland/methodlist#44]
Jag satt och funderade på en grej som skulle kunna vara najs, men bara om det funkar på ett enkelt sätt och inte blir för mycket jobb.
Det jag funderade på är en snabb överblicks-banner som för varje prov, med enkla ikoner, visar vad som är viktigt för just det provet, exempelvis vilket rör det ska tas i, om det ska ljuskyddas eller om det måste läggas på is direkt.
Idén har jag helt skamlöst snott från FASS, se ex 
http://www.fass.se/LIF/product?userType=0&nplId=20031111000058
där man snabbt, med ikoner, ser att detta läkemedel ex bl.a . är föremål för "utökad övervakning"

Mitt förslag var då t.ex att i exceldokumentet lägga till kolumner för dessa ikoner, och skriva typ "Ja" eller "X" eller nåt i motsvarande kolumn om provet ska ha den ikonen. (Allra helst hade jag ju sett att man kunde ha checkboxar, men av nån idiotisk anledning verkar inte det fungera (att snabbt koppla massa checkboxar till olika rutor...))

![snabb-ikoner](https://cloud.githubusercontent.com/assets/20255952/18513228/e74086d0-7a8c-11e6-8a83-69bf16d61604.png)

det här skulle vara de 6 olika ikoner jag isf funderar på.

Vad säger du?

**Comment by gustavsobel** [comment]
juste, det där förklarande fönstret skulle isf dyka upp när man för muspekaren över motsv. ikon...

**Comment by dnjstrom** [comment]
Det kan vi göra! Fixar du stora varianter av ikonerna, centrerade i en 512
px stor låda?
