### ISSUE TITLE
Nya, icke-officiella analyser i en ny branch?

### ISSUE THREAD

**Issue by gustavsobel** [LabVastmanland/methodlist#46]
Nu när deadline närmar sig och alla externa analyser ska ligga uppe officiellt behöver vi ju nåt sätt att kunna fortsätta lägga upp nya analyser, men utan att de dyker upp på den officiella sidan (förrän de är godkända). Jag vet inte riktigt hur det funkar med branches, men skulle det vara ett alternativ, eller att man skriver nåt i excelfilen så att sidan ignorerar alla analyser med "IGNORE" typ? Har du något annat förslag?

**Comment by dnjstrom** [comment]
Detta är inte riktigt praktiskt möjligt med vår enkla setup tyvärr. I teorin skulle man iofs kunna lägga in en PUBLISHED flagga typ och en gömd route för att se de, typ '/unpublished'. Vi kan inte riktigt begränsa en användare som vill komma åt dem kanske, men vi skulle ju faktiskt kunna göra det relativt svårt att komma åt dem 👍

**Comment by gustavsobel** [comment]
Jag har pratat med Johan och detta är egentligen inget bekymmer, de analyser som läggs upp löpande kommer, per definition, vara validerade

**Comment by gustavsobel** [comment]
Kanske att man lägger in nån text (typ som den röda disclaimer-texten, fast intr såå obvious) där det står typ "Arbetsversion, uppdayeras kontinuerligt"
