### ISSUE TITLE
Ordna så man kan länka direkt till ett provtagning

### ISSUE THREAD

**Issue by dnjstrom** [LabVastmanland/methodlist#47]

**Comment by dnjstrom** [comment]
ID ska hämtas direkt från excelen

**Comment by dnjstrom** [comment]
Hmmm.. Jag får inte det här att funka tyvärr. Deep-linking för Single Page Applications är ett känt problem som jobbas på (https://github.com/isaacs/github/issues/408) men som det inte egentligen finns någon bra lösning för i dagsläget. Finns ett ganska bökigt hack i tråden ovan, men lutar i princip åt att bygga en egen server istället i så fall. :/

**Comment by gustavsobel** [comment]
Vi kan ju höra med Johan hur viktig denna funktion är, om det verkligen är värt det jobbet
